# Generated by Django 3.0.7 on 2020-07-17 15:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('power_crystals', models.IntegerField(default=10)),
                ('hp_current', models.IntegerField(default=10)),
                ('hp_max', models.IntegerField(default=10)),
                ('gold', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sir Knight', max_length=50)),
                ('power_crystals', models.IntegerField(default=10)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('hp_current', models.IntegerField(default=10)),
                ('hp_max', models.IntegerField(default=10)),
                ('gold', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=10)),
                ('heal_cost', models.IntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
