# Generated by Django 3.0.7 on 2020-06-28 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
