# Generated by Django 3.0.7 on 2020-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200628_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='damage',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='enemy',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemy',
            name='hp_current',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='enemy',
            name='hp_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='enemy',
            name='power_crystals',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='damage',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='hp_current',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='hp_max',
            field=models.IntegerField(default=10),
        ),
    ]
