# Generated by Django 3.0.7 on 2020-07-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200714_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='name',
            field=models.TextField(default='', max_length=50),
        ),
    ]
