# Generated by Django 3.0.7 on 2020-07-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_enemy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='heal_cost',
            field=models.IntegerField(default=0),
        ),
    ]
